//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
//Master Data
export const GET_MASTER_DATA_REQUEST = 'GET_MASTER_DATA_REQUEST';
export const GET_MASTER_DATA_SUCCESS = 'GET_MASTER_DATA_SUCCESS';
export const GET_MASTER_DATA_FAILED = 'GET_MASTER_DATA_FAILED';
export const PROCESS_MASTER_DATA = 'PROCESS_MASTER_DATA';
//register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
//OTP register
export const OTP_REGISTER_REQUEST = 'OTP_REGISTER_REQUEST';
export const OTP_REGISTER_SUCCESS = 'OTP_REGISTER_SUCCESS';
export const OTP_REGISTER_FAILED = 'OTP_REGISTER_FAILED';

//UpdateProfile
export const UPDATE_NICKNAME_PROFILE = 'UPDATE_NICKNAME_PROFILE';
export const UPDATE_BIRTHDAY_PROFILE = 'UPDATE_BIRTHDAY_PROFILE';
export const UPDATE_NATIONALITY_PROFILE = 'UPDATE_NOTIONALITY_PROFILE';
export const UPDATE_GENDER_PROFILE = 'UPDATE_GENDER_PROFILE';
export const UPDATE_REFECHANNEL_PROFILE = 'UPDATE_REFECHANNEL_PROFILE';
export const UPDATE_EMAILFACEBOOK_PROFILE = 'UPDATE_EMAILFACEBOOK_PROFILE';
export const UPDATE_HOMETOWN_PROFILE = 'UPDATE_HOMETOWN_PROFILE';
export const UPDATE_JOB_PROFILE = 'UPDATE_JOB_PROFILE';
export const UPDATE_HEIGHT_PROFILE = 'UPDATE_HEIGHT_PROFILE';
export const UPDATE_MARRY_PROFILE = 'UPDATE_MARRY_PROFILE';
export const UPDATE_ENTRYDATE_PROFILE = 'UPDATE_ENTRYDATE_PROFILE';
export const UPDATE_RESIDENTCYSTATUS_PROFILE =
  'UPDATE_RESIDENTCYSTATUS_PROFILE';
export const UPDATE_PERIODOFSTAY_PROFILE = 'UPDATE_PERIODOFSTAY_PROFILE';
export const UPDATE_LANGUAGE_PROFILE = 'UPDATE_LANGUAGE_PROFILE';
export const UPDATE_LEVELLANGUAGE_PROFILE = 'UPDATE_LEVELLANGUAGE_PROFILE';
export const UPDATE_OCCUPATION_PROFILE = 'UPDATE_OCCUPATION_PROFILE';
export const UPDATE_ANNUALINCOME_PROFILE = 'UPDATE_ANNUALINCOME_PROFILE';
export const UPDATE_MARRIAGEINTENTIONS_PROFILE =
  'UPDATE_MARRIAGEINTENTIONS_PROFILE';
export const UPDATE_MARRIAGEHISTORY_PROFILE = 'UPDATE_MARRIAGEHISTORY_PROFILE';
export const UPDATE_CURRENTROOMATE_PROFILE = 'UPDATE_CURRENTROOMATE_PROFILE';
export const UPDATE_FAMILY_PROFILE = 'UPDATE_FAMILY_PROFILE';
export const UPDATE_WORKAFTERMARRIAGE_PROFILE =
  'UPDATE_WORKAFTERMARRIAGE_PROFILE';
export const UPDATE_INTERESTS_PROFILE = 'UPDATE_INTERESTS_PROFILE';
export const UPDATE_AGETOWANT_PROFILE = 'UPDATE_AGETOWANT_PROFILE';
export const UPDATE_DESIREDPARTNER_PROFILE = 'UPDATE_DESIREDPARTNER_PROFILE';
export const UPDATE_DESIRED_PLACE_LIVE = 'UPDATE_DESIRED_PLACE_LIVE';
export const UPDATE_LIVING_AREA_PROFILE = 'UPDATE_LIVING_AREA_PROFILE';
export const UPDATE_AVATAR_IMAGE_ID_PROFILE = 'UPDATE_AVATAR_IMAGE_ID_PROFILE';
export const UPDATE_PROFILE_IMAGE_MANAGEMENT_CODE =
  'UPDATE_PROFILE_IMAGE_MANAGEMENT_CODE';
export const UPDATE_PROFILE_LOCATION = 'UPDATE_PROFILE_LOCATION';
// export const SAVE_DATA_PROFILE = "SAVE_DATA_PROFILE";
// export const SAVE_DATA_PROFILE = "SAVE_DATA_PROFILE";
// export const SAVE_DATA_PROFILE = "SAVE_DATA_PROFILE";
export const SEND_VERIFICATION_REQUEST = 'SEND_VERIFICATION_REQUEST';
export const SEND_VERIFICATION_REQUEST_SUCCESS =
  'SEND_VERIFICATION_REQUEST_SUCCESS';
export const SEND_VERIFICATION_REQUEST_FAILED =
  'SEND_VERIFICATION_REQUEST_FAILED';

// get Profile
export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_CHAT_DATA = 'UPDATE_CHAT_DATA';
export const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';
export const DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE';
export const UPDATE_CHAT_SETTINGS = 'UPDATE_CHAT_SETTINGS';
export const CLEAR_ERROR_LOGIN = 'CLEAR_ERROR_LOGIN';
export const UPDATE_LIKE_COUNT = 'UPDATE_LIKE_COUNT';
export const REGISTER_RESET = 'REGISTER_RESET';
export const UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS';

export const INIT_FORM_SEARCH = 'INIT_FORM_SEARCH';
export const INIT_SEARCH = 'INIT_SEARCH';
export const INIT_APP_LINK = 'INIT_APP_LINK';
export const GET_APP_LINKS = 'GET_APP_LINKS';
export const WAITING_PAYMENT = 'WAITING_PAYMENT';

// CALENDAR

export const UPDATE_CALENDAR = 'UPDATE_CALENDAR';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const RESET_CALENDAR = 'RESET_CALENDAR';
export const UPDATE_MEDICAl_HISTORY = 'UPDATE_MEDICAl_HISTORY';
export const RESET_MEDICAl_HISTORY = 'RESET_MEDICAl_HISTORY';


