import { StyleSheet, Dimensions } from 'react-native';
import Colors from '@config/styles';
let { width, height } = Dimensions.get('window');
width = width > 600 ? 600 : width;
export const styles = StyleSheet.create({
  item: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.color.COLOR_ALABASTER,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginVertical: 8,
    borderRadius: 10,
    minHeight: 'auto',
  },
  titleText: {
    color: '#696A6A',
    fontStyle: 'normal',
    fontWeight: 'normal',
    lineHeight: 24,
    flex: 1,
    // width: '50%',
    fontSize: 14,
  },

  textDefault: {
    color: '#272D2D',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: 'normal',
    lineHeight: 24,
    textAlign: 'right',
  },
  textValue: {
    color: '#5BB7AD',
    fontStyle: 'normal',
    fontSize: 13,
    fontWeight: 'normal',
    lineHeight: 24,
    // maxWidth: '80%',
    // backgroundColor: "red",
    textAlign: 'right',
    // flex: 1,
    maxWidth: '50%',
    maxWidth: 207,
  },
  // css popup
  button: {
    backgroundColor: 'lightblue',
    padding: 12,
    margin: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  modalContent: {
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 16,
    paddingBottom: 120,
    margin: 0,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    maxHeight: 0.7 * height,
    minHeight: 330,
  },
  dFlex: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    // width: "100%",
    // height: 0.5 * height - 100,
    paddingTop: 25,
    textAlign: 'center',
    // top: 0,
    // position: "absolute",
  },

  modalTitleTxt: {
    color: Colors.color.COLOR_OUTER_SPACE,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 16,
    // lineHeight: 27,
    // marginBottom: 20,
    // marginTop: 5,
  },

  //css button
  row: {
    width: '100%',
    // paddingHorizontal: 19,
  },
  rowLeft: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  rowSpaceBetween: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  btnGroup: {
    paddingTop: 15,
    paddingBottom: 30,
    paddingHorizontal: 16,
    borderRadius: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    margin: 'auto',
    width: width - 2 * 25,
  },

  scrollview: {
    width: '100%',
    height: height * 0.5,
    marginTop: 20,
  },

  // css checkbox
  checkItem: {
    paddingVertical: 10,
    width: '100%',
    backgroundColor: 'gray',
    marginBottom: 2,
  },
  checkbox: {
    width: 24,
    height: 24,
    paddingTop: 2,
    marginTop: 5,
    borderWidth: 1,
    borderColor: Colors.color.COLOR_NEW_YORK_PINK,
    borderRadius: 5,
  },
  selectedRow: {
    backgroundColor: Colors.color.COLOR_CHABLIS,
    minWidth: width - 72,
    borderRadius: 15,
    marginTop: 8,
    borderBottomColor: Colors.color.COLOR_WHITE,
  },
  label: {
    maxWidth: width - 120,
  },
  rowWeb: {
    maxWidth: width - 64,
  },
  labelRow: {
    paddingRight: 20,
    paddingHorizontal: 8,
    width: '90%',
    minHeight: 36,
    // flexDirection:'row',
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  rowCheckbox: {
    width: width - 64,

    marginTop: 8,
    alignItems: 'flex-start',
    borderRadius: 15,
    paddingVertical: 12,
    backgroundColor: 'transparent',
    borderBottomColor: Colors.color.COLOR_WHITE,
  },
  rowCheckbox2: {
    padding: 0,
    paddingHorizontal: 15,
    marginTop: 8,
    borderRadius: 15,
    backgroundColor: 'transparent',
    borderBottomColor: Colors.color.COLOR_WHITE,
  },

  wrapperVertical: {
    // flex: 1,
    // width: '100%',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    margin: 'auto',
    color: 'black',
    // backgroundColor: 'red',
  },
  OptionWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    // width:"100%",
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#3C3C43',
  },
  containerScroll: {
    paddingTop: 60,
    // paddingBottom: 30,
    paddingVertical: 30,
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    // backgroundColor: 'yellow',
  },
  scrollPicker: {
    width: 60,
  },
  textError: {
    // marginTop: 10,
    fontSize: 14,
    // lineHeight: 16,
    color: Colors.color.COLOR_RED,
  },
  rangeTitle: {
    fontSize: 16,
    fontWeight: '500',
    paddingVertical: 5,
    lineHeight: 20,
    marginBottom: 24,
    textAlign: 'center',
    backgroundColor: '#f8f8f8',
  },
  textFromTo: {
    textAlign: 'left',
    fontSize: 16,
    lineHeight: 18,
    paddingLeft: 5,
  },
});
