require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
# use_frameworks!
target 'TCare' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
    )
    permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Firebase'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'LineSDKSwift', '~> 5.0'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'RNIap', :path => '../node_modules/react-native-iap'
  pod 'GoogleSignIn', '~> 6.1.0'
  pod 'FBSDKLoginKit'
  target 'TCareTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
    react_native_post_install(installer)
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end
  end
end

target 'TCare-tvOS' do
  # Pods for TCare-tvOS

  target 'TCare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
