import {StyleSheet, Dimensions} from "react-native";
const {width, height} = Dimensions.get("window");
const styles = StyleSheet.create({
  avatarContainer: {
    width: 32,
    height: 32,
    borderRadius: 32 / 2,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  avatar: {width: 48, height: 48, borderRadius: 48 / 2, alignSelf: "center"},
  name: {fontSize: 22, marginTop: 10, color: "white", fontWeight: "bold"},
  statusLabel: {fontSize: 16, color: "white", marginTop: 10},
  lastMessages: {fontWeight: "normal", lineHeight: 24},
  contentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    flex: 1,
  },
  bottomView: {
    backgroundColor: "rgba(0,0,0,0.4)",
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    height: 200,
    justifyContent: "flex-start",
  },
  yourVideo: {
    // // flex: 1,
    // // backgroundColor: "red",
    backgroundColor: "transparent",
    position: "absolute",
    width: 132,
    height: 200,
    bottom: 140,
    right: 50,
    borderColor: "#fff",
    borderWidth: 2,
    zIndex: 999,
  },
  videoMain: {
    flex: 1,
    position: "relative",
    backgroundColor: "#eaeaea",
  },
  remoteVideo: {
    position: "absolute",
    zIndex: 1,
    // flex: 1,
    width: width,
    height: height,
    backgroundColor: "#f2f2f2",
  },
  actionButton: {
    tintColor: "white",
  },
  bottomTool: {
    position: "absolute",
    zIndex: 5,
    height: 143,
    width: "100%",
    flexDirection: "row",
    paddingHorizontal: 40,
    bottom: 0,
    alignItems: "center",
    justifyContent: "space-between",
  },
  overBackground: {
    zIndex: 2,
    position: "absolute",
    height: 143,
    bottom: 0,
  },
  modalPopup: {justifyContent: "flex-end", flex: 1, margin: 0},
  viewPopup: {
    height: height - 60,
    backgroundColor: "white",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingVertical: 25,
    paddingHorizontal: 28,
  },
});
export default styles;
